<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrossLedger.Application\CrossLedger.Application.csproj" />
    <ProjectReference Include="..\CrossLedger.Infrastructure\CrossLedger.Infrastructure.csproj" />
    <ProjectReference Include="..\CrossLedger.Providers\CrossLedger.Providers.csproj" />
    <ProjectReference Include="..\CrossLedger.Shared\CrossLedger.Shared.csproj" />
  </ItemGroup>

</Project>
